import type { Competition } from './competitions';

export const mockCompetitions: Competition[] = [
  {
    id: 'mock-1',
    image: null,
    name: 'Кубок України з хіп-хопу',
    description: 'Відкритий чемпіонат з хіп-хопу серед солістів, дуетів та команд.',
    location: 'Київ, Палац спорту',
    organizer: 'Оргкомітет "HipHop Cup"',
    dateFrom: '2026-09-20',
    dateTo: '2026-09-21',
    registrationFrom: '2026-08-01',
    registrationTo: '2026-09-10',
    contactNumber: '+380 67 123 4567',
    contactEmail: 'info@hiphopcup.ua',
    paymentDetails: null,
    ownerId: 'mock-owner-1',
    owner: { id: 'mock-owner-1', name: 'Оргкомітет "HipHop Cup"' },
  },
  {
    id: 'mock-2',
    image: null,
    name: 'Всеукраїнський фестиваль бальних танців',
    description: 'Фестиваль-конкурс з бальних танців для всіх вікових категорій.',
    location: 'Львів, Палац культури ім. Гната Хоткевича',
    organizer: 'ГО "Танцювальний рух"',
    dateFrom: '2026-11-15',
    dateTo: '2026-11-16',
    registrationFrom: '2026-10-01',
    registrationTo: '2026-10-25',
    contactNumber: '+380 63 987 6543',
    contactEmail: 'contact@balldancefest.ua',
    paymentDetails: null,
    ownerId: 'mock-owner-2',
    owner: { id: 'mock-owner-2', name: 'ГО "Танцювальний рух"' },
  },
  {
    id: 'mock-3',
    image: null,
    name: 'Літній танцювальний марафон',
    description: 'Багатоденний конкурс із сучасних танцювальних напрямків.',
    location: 'Одеса, Спортивний комплекс "Чорноморець"',
    organizer: 'Студія танцю "Ритм"',
    dateFrom: '2026-08-10',
    dateTo: '2026-08-16',
    registrationFrom: '2026-07-01',
    registrationTo: '2026-08-05',
    contactNumber: '+380 50 555 1122',
    contactEmail: 'summer@dancemarathon.ua',
    paymentDetails: null,
    ownerId: 'mock-owner-3',
    owner: { id: 'mock-owner-3', name: 'Студія танцю "Ритм"' },
  },
  {
    id: 'mock-4',
    image: null,
    name: 'Кубок весни з сучасного танцю',
    description: 'Щорічний змагальний конкурс серед шкіл сучасного танцю.',
    location: 'Харків, ПС "Локомотив"',
    organizer: 'Оргкомітет "Modern Cup"',
    dateFrom: '2026-05-10',
    dateTo: '2026-05-11',
    registrationFrom: '2026-04-01',
    registrationTo: '2026-04-25',
    contactNumber: '+380 66 222 3344',
    contactEmail: 'spring@moderncup.ua',
    paymentDetails: null,
    ownerId: 'mock-owner-4',
    owner: { id: 'mock-owner-4', name: 'Оргкомітет "Modern Cup"' },
  },
];

export function getMockCompetitionById(id: string): Competition | undefined {
  return mockCompetitions.find((c) => c.id === id);
}
